"""empty message

Revision ID: 549aff82dedb
Revises: c8ff967f0849
Create Date: 2024-11-05 21:27:36.303352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549aff82dedb'
down_revision = 'c8ff967f0849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'goal', ['goal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###
